version: '3'
services:

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - PORT=3000
    depends_on:
      - mongodb

  api:
    build:
      context: ./api
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - PORT=5000
      - APP_MONGO_URL=mongodb
      - APP_MONGO_PORT=27017
      - API_HOST=api
    depends_on:
      - mongodb

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth
