version: "2"

services:
    client:
        image: spacebits/dndtracker:client
        build:
          context: ./client
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./client:/client
            - /client/node_modules
        links:
            - server
        depends_on:
            - server
        networks:
            - dndnet
        environment:
            - APP_SERVER_URL=server

    server:
        image: spacebits/dndtracker:server
        build:
          context: ./server
        restart: always
        ports:
           - "3001:3001"
        tty: true
        volumes:
            - ./server:/server
            - /server/node_modules
        depends_on:
            - mongodb
        networks:
            - dndnet
        environment:
          - APP_MONGO_URL=mongodb

    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - "27017:27017"
        command: mongod --noauth --smallfiles
        networks:
            - dndnet

networks:
    dndnet:
        driver: bridge
