version: "2"

services:
    client:
        build: ./client
        image: dndtracker_client
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./client:/client
            - /client/node_modules
        links:
            - server
        networks:
            - webappnetwork
        container_name: dndtracker_client

    server:
        build: ./server
        image: dndtracker_server
        restart: always
        ports:
           - "3001:3001"
        tty: true
        volumes:
            - ./server:/server
            - /server/node_modules
        depends_on:
            - mongodb
        networks:
            - webappnetwork 
        container_name: dndtracker_server
        environment:
          - APP_MONGO_URL=mongodb
    
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        volumes:
            - ./data-node:/data/db
        ports:
            - "27017:27017"
        command: mongod --noauth --smallfiles
        networks:
            - webappnetwork

networks:
    webappnetwork:
        driver: bridge
