version: '3'
services:

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    depends_on:
      - mongodb

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    env_file:
      - .env
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      - APP_MONGO_URL=mongodb
      - APP_MONGO_PORT=27017
    depends_on:
      - mongodb

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '8080:80'
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./data-node:/data/db
    command: mongod --noauth --smallfiles
