version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  build-backend:
    working_directory: ~/project/backend
    executor: node/default
    steps:
      - checkout

  build-frontend:
    working_directory: ~/project/frontend
    executor: node/default
    steps:
      - checkout
      - run: yarn build

  run-backend-tests:
    working_directory: ~/project/backend
    executor: node/default
    steps:
      - run: yarn test

  run-frontend-tests:
    working_directory: ~/project/frontend
    executor: node/default
    steps:
      - run: yarn test

workflows:
  node-tests:
    jobs:
      - build-backend
      - build-frontend
      - run-backend-tests
      - run-frontend-tests
