version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  build-backend:
    executor: node/default
    steps:
      - checkout

  build-frontend:
    executor: node/default
    steps:
      - checkout
      - run: |
          cd frontend
          yarn build

  run-backend-tests:
    executor: node/default
    steps:
      - run: |
          cd backend
          yarn test

  run-frontend-tests:
    executor: node/default
    steps:
      - run: |
          cd frontend
          yarn test

workflows:
  node-tests:
    jobs:
      - build-backend
      - build-frontend
      - run-backend-tests:
          requires:
            - build-backend
      - run-frontend-tests:
          requires:
            - build-frontend
