version: "3"

services:
  client:
    image: dndtracker:client
    build:
      context: ../client
    restart: on-failure
    ports:
    - "3000:3000"
    volumes:
    - ../client:/client
    - /client/node_modules
    depends_on:
    - api
    networks:
    - dndnet
    environment:
    - APP_SERVER_URL=server

  api:
    image: dndtracker:server
    build:
      context: ../api
    restart: on-failure
    ports:
    - "3001:3001"
    tty: true
    volumes:
    - ../api:/api
    - /api/node_modules
    depends_on:
    - characterService
    networks:
    - dndnet
    environment:
    - APP_MONGO_URL=mongodb

  characterService:
    image: dndtracker:character
    build:
      context: ../character-service
    restart: on-failure
    ports:
    - "3002:3002"
    tty: true
    volumes:
    - ../character-service:/character-service
    - /character-service/node_modules
    depends_on:
    - mongodb
    networks:
    - dndnet
    environment:
    - PORT=3002
    - HOST=0.0.0.0
    - APP_MONGO_URL=mongodb
    - APP_MONGO_PORT=27017

  mongodb:
    image: mongo
    restart: on-failure
    container_name: mongodb
    volumes:
    - ../data-node:/data/db
    ports:
    - "27017:27017"
    command: mongod --noauth --smallfiles
    networks:
    - dndnet

networks:
  dndnet:
    driver: bridge
