version: "2"

services:
  characterBase:
    image: node:11
    volumes:
    - character_nodemodules:/usr/src/service/node_modules
    - ../characterService/:/usr/src/service/
    working_dir: /usr/src/service/

  characterInstall:
    extends:
      service: characterBase
    command: npm i

volumes:
  character_nodemodules:
    external: true
    
  api_nodemodules:
    external: true
