version: "2"

services:
  # Base for the character service, that leverages the external node module volume
  characterBase:
    image: node:11
    volumes:
    - character_nodemodules:/usr/src/service/node_modules
    - ../characterService/:/usr/src/service/
    working_dir: /usr/src/service/

  characterInstall:
    extends:
      service: characterBase
    command: npm i

  # Base for the apiGateway service, that leverages the external node module volume
  apiGatewayBase:
    image: node:11
    volumes:
    - apiGateway_nodemodules:/usr/src/service/node_modules
    - ../api/:/usr/src/service/
    working_dir: /usr/src/service/

  apiGatewayInstall:
    extends:
      service: apiGatewayBase
    command: npm i

volumes:
  character_nodemodules:
    external: true
  apiGateway_nodemodules:
    external: true
