// Error
export const GET_ERRORS = "GET_ERRORS";

// Auth
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

// Character
export const FETCH_USER = "FETCH_USER";
export const FETCH_CHARACTERS = "FETCH_CHARACTERS";
export const ADD_CHARACTER = "ADD_CHARACTER";
export const DELETE_CHARACTER = "DELETE_CHARACTER";

// Campaign
export const FETCH_CAMPAIGN = "FETCH_CAMPAIGN";
export const FETCH_PUBLIC_CAMPAIGNS = "FETCH_PUBLIC_CAMPAIGNS";
export const JOIN_CAMPAIGN = "JOIN_CAMPAIGN";
export const LEAVE_CAMPAIGN = "LEAVE_CAMPAIGN";
